### ISSUE TITLE
Kinect 2 not found on Windows 7

### ISSUE THREAD

**Issue by xlz** [daynix/UsbDk#21] opened 2016-02-28 00:41 UTC
Similar to #19.

Files:
[UsbDkController-n.txt](https://github.com/daynix/UsbDk/files/149662/UsbDkController-n.txt)
[MyUsbTree.txt](https://github.com/daynix/UsbDk/files/149663/MyUsbTree.txt)
[UsbDkTrace.etl.txt](https://github.com/daynix/UsbDk/files/149664/UsbDkTrace.etl.txt)
(usbview.exe crashes when saving to xml.)

**Comment by dmitryfleytman** [comment] 2016-02-28 06:11
What version of UsbDk are you using?

**Comment by xlz** [comment] 2016-02-28 06:19
UsbDk_1.0.12_x64

**Comment by dmitryfleytman** [comment] 2016-02-28 07:55
Text extracted from .etl file:

[UsbDk]<lambda_a257bb3effc18ee15b227ef0411f37ef>::operator() Starting relations array processing:
[UsbDk]CDeviceRelations::Dump Array size: 1 (ptr: FFFFFA8009B78B00)
[UsbDk]CDeviceRelations::ForEachIf<bool #0: FFFFFA80067B1570
[UsbDk]UsbDkSendUrbSynchronously Send URB IRP Error 0xc000000d(STATUS_INVALID_PARAMETER)
[UsbDk]CUsbDkHubFilterStrategy::RegisterNewChild Cannot query device descriptor
[UsbDk]<lambda_a257bb3effc18ee15b227ef0411f37ef>::operator() Finished relations array processing
[UsbDk]<lambda_a257bb3effc18ee15b227ef0411f37ef>::operator() Starting relations array processing:
[UsbDk]CDeviceRelations::Dump Array size: 2 (ptr: FFFFFA8007757B80)
[UsbDk]CDeviceRelations::ForEachIf<bool #0: FFFFFA800ACC1600
[UsbDk]CDeviceRelations::ForEachIf<bool #1: FFFFFA80067B1570
[UsbDk]UsbDkSendUrbSynchronously Send URB IRP Error 0xc000000d(STATUS_INVALID_PARAMETER)
[UsbDk]CUsbDkHubFilterStrategy::RegisterNewChild Cannot query device descriptor
[UsbDk]UsbDkSendUrbSynchronously Send URB IRP Error 0xc000000d(STATUS_INVALID_PARAMETER)
[UsbDk]CUsbDkHubFilterStrategy::RegisterNewChild Cannot query device descriptor
[UsbDk]<lambda_a257bb3effc18ee15b227ef0411f37ef>::operator() Finished relations array processing
[UsbDk]UsbDkEvtDeviceAdd Entry
[UsbDk]CUsbDkFilterDevice::Create Entry
[UsbDk]CWdfDevice::CacheDeviceName Newly created device name is \Device\UsbDkFilter18
[UsbDk]CRegText::Dump ID: USB\VID_045E&PID_02D9
[UsbDk]CUsbDkFilterDevice::CStrategist::SelectStrategy Cannot query cached device descriptor
[UsbDk]CUsbDkFilterDevice::DefineStrategy Not attached
[UsbDk]UsbDkEvtDeviceAdd Exit 0xc00000bb(STATUS_NOT_SUPPORTED)
[UsbDk]CUsbDkFilterDevice::ContextCleanup Entry

**Comment by dmitryfleytman** [comment] 2016-02-28 07:56
According to the trace file device does not provide device descriptors. What is the difference since the last time when it worked?

**Comment by xlz** [comment] 2016-02-28 08:15
Last time it was Windows 8.1 with intel xhci. This is NEC controller on Windows 7.

libusb with libusbK backend works though.

**Comment by xlz** [comment] 2016-02-29 21:31
Anything can I do or any more data can I provide?

**Comment by dmitryfleytman** [comment] 2016-03-01 08:56
Not for now, thanks. I will take a look at this as soon as possible.

**Comment by dmitryfleytman** [comment] 2017-02-02 12:44
Duplicate of #33
Fixed by db95b4651e079e59353d8bafa84cc5ad23c4f2b1

**Closed by dmitryfleytman** 2017-02-02 12:44 UTC
