### ISSUE TITLE
Installation o Windows 10 blocks all USB 

### ISSUE THREAD

**Issue by zeroxm** [daynix/UsbDk#42] opened 2017-03-11 05:39 UTC
Tried to install on Windows 10, as recommended in this emulation project,  https://wiki.dolphin-emu.org/index.php?title=USB_Passthrough#In_5.0-2352_and_newer

I know it's not the first time this is reported, but I you should consider marking the lib linked above to be incompatible with Windows 10.

I'll try to get a PS/2 keyboard and Uninstall the driver tomorrow. I'll try and report back and give some more info about it. Currently I can say:
- Windows says it's an unsigned driver,  maybe this is what's causing this behavior
- There is a way to test whether adding permission to unsignes drivers makes any difference,I'll try to do it

**Comment by zeroxm** [comment] 2017-03-11 17:54
Confirmed.

If you change the boot options so it disable driver signature enforcement the simptoms disapear (currently I still can't boot without it)

**Comment by dmitryfleytman** [comment] 2017-03-13 13:49
Hi,

You should be able to boot in safe mode and uninstall UsbDk.

Are you using Windows10 RS1 with secure boot enabled?

~Dmitry

**Comment by zeroxm** [comment] 2017-03-13 13:56
I was on Windows 10,  and yes I was able to do so,  but turns out just uninstalling it using Control Panel doesn't fix this, it looks like the Driver were still there.

I tried something stupid after and thought I could manually delete the Driver, and Windows try and fix this.... but no.

**Comment by dmitryfleytman** [comment] 2017-03-13 13:57
You need to uninstall the driver and then reboot the system.

**Comment by zeroxm** [comment] 2017-03-13 13:58
Oh and Yes, secure boot didn't let me mess with driver signature checking.

In the end I had to reinstall windows  (formatting it) because I needed the PC to work again.

**Comment by dmitryfleytman** [comment] 2017-03-13 13:59
Sorry to hear that, we are working on solution that will include full signature suitable for Win10 RS1 with secure boot and verification of driver functionality during installation.

**Comment by zeroxm** [comment] 2017-03-13 14:01
I did Unninstall and reboot, but the USB wouldn't work unless I did something similar to Solution 1, shown here.

http://windowsreport.com/driver-signature-enforcement-windows-10/

**Comment by zeroxm** [comment] 2017-03-13 14:02
Anyway I hope the info provided helps, if you need something else, please, do ask.

**Comment by dmitryfleytman** [comment] 2017-03-13 14:02
Thanks!

**Comment by Waishon** [comment] 2017-03-31 18:42
Is there a new status about this issue?

**Comment by MarcusWichelmann** [comment] 2017-03-31 18:44
Are you still working on this?
We planned to recommend the use of this driver to pupil of our school to be able to connect to our spice VMs, but since it just killed my Windows10 PC and I've read this thread we probably will not for near future.

I've been able to recover the USB support of my PC by logging in via RDP and uninstalling the driver in device-manager.

**Comment by dmitryfleytman** [comment] 2017-04-02 10:51
Hi @MarcusWichelmann,

Yes, we are working on this. We expect that the first public release with all signatures and full Windows 10 support will be public in 2-3 weeks.

Thanks for using UsbDk,
Dmitry.

**Comment by dmitryfleytman** [comment] 2017-04-20 08:14
Fixed in v1.00-19

**Closed by dmitryfleytman** 2017-04-20 08:14 UTC

**Comment by matrix65** [comment] 2017-05-09 11:00
With v1.00 - 19, on windows 10 x64,  version 1703, 15063.138 build, the driver is still blocked. 
Running cmd(admin) UsbDkController.exe -i  only got "UsbDk driver installation failed"

**Comment by zeroxm** [comment] 2017-05-09 16:01
I've tested the driver on v1.00-19 and it worked as intended. 
Maybe something more specific on your installation?

**Comment by MarcusWichelmann** [comment] 2017-05-09 16:07
The driver works as expected here, now. I can confirm, that this issue is fixed

**Comment by dmitryfleytman** [comment] 2017-05-10 18:23
Hi @matrix65 , are you installing officially released binaries or build the driver yourself?

In case you're using official binaries, could you please collect [user mode logs](https://github.com/daynix/UsbDk/blob/master/Documentation/Tracing.txt#L15) to see what's wrong with the installation?

**Comment by matrix65** [comment] 2017-05-11 03:27
It turns out that it was the external usb drive that blocked the installation. After removing it and a clean reboot, the driver is sucessfully installed. 
Thanks for all the above quick responses to help me.
